version: '3'

tasks:
  ansible-ping:
    cmds:
      - ansible pve_home -m ping -i ansible/homelab.yaml
    silent: true
  ansible-requirements:
    cmds:
      - cd ansible && ansible-galaxy install -r requirements.yaml
  ansible-playbook:
    cmds:
      - cd ansible && ansible-playbook site.yaml -i homelab.yaml
  ansible-pve:
    cmds:
      - cd ansible && ansible-playbook site.yaml -i homelab.yaml -l pve
  ansible-pg:
    cmds:
      - cd ansible && ansible-playbook site.yaml -i homelab.yaml -l postgresql
  ansible-k3s:
    cmds:
      - cd ansible && ansible-playbook site.yaml -i homelab.yaml -l k3s_cluster
