ansible_port: ENC[AES256_GCM,data:smCXNA==,iv:+CQr84bd1b1Cp/7n/JVwn1sbIUY5xLFiPmQkYt9FR+k=,tag:zvh8qeo066ix59NyQ/LEuA==,type:int]
ansible_user: ENC[AES256_GCM,data:+9c=,iv:BnTBevHEMXbBZe1oYJ7pZICYL7QTuA3J1aoTTVNwyrU=,tag:ksM76zz/C0LtrOoeZzHDIw==,type:str]
has_gpu: ENC[AES256_GCM,data:chR9X84=,iv:qEcpHSQpmJPZqmnpqe63klJ4QhYgCy1GkfVc9xP65iw=,tag:QxBIhVZD3JvXw65A7vMzFA==,type:bool]
mounts: []
#ENC[AES256_GCM,data:cES8Nfo=,iv:9B2Cv/s2WTiRWoJGXWQzhxEP3xeFqVTP3kHonWP8B4I=,tag:eGpTpDP+RKNSyN7N29cjig==,type:comment]
k3s_install_hard_links: ENC[AES256_GCM,data:2rQrlw==,iv:jmpdf0ui5DX5kU5GFUnZX2inehE4luZIteZYafHLAAE=,tag:K3gNta8D4vtjGHhX8J/pfg==,type:bool]
k3s_become: ENC[AES256_GCM,data:CyIMcQ==,iv:ZfZzGYj6FTitTGJRDb7P1qagZ2+PDTcKJU90e+wKJcs=,tag:YhGu4o0jcioPQtC/cD0FcQ==,type:bool]
#ENC[AES256_GCM,data:69hqT+uJNfhjohsYMa0o6EZZR/0e9HQAm3SCrZ3ry9mOW5sW0mzJ4Q==,iv:likrjz9aRo5j3Do7VApnkKDc6El5GOoZls5DJXGFqrs=,tag:VEtiIO29BcnkPcG3uDs9uA==,type:comment]
k3s_use_unsupported_config: ENC[AES256_GCM,data:9uxKhg==,iv:mfRgCBVvRnnPCJnoSx26PNA3nH/KTgc00k6P0lEnBOc=,tag:+R9HctF2pW3L6Wo9FGSptg==,type:bool]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wdhud9akfa4ua4urh3q6epn959wnd6yu0cmva7kdukx0kmvkxygst9ycau
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHQkNEd0FZUTVnYnE2bkVu
            anlIVlgxMzJ6R2F2WHRicXVCV2xCU3lMaFRnClEvLzE5KzFaV2w2VVYrWmZ2aTdV
            VnhVQmV5V1BBbmZsOFpDeUhhZjExNWcKLS0tIEU5WHl1WFdETmwwOXU3dFkyZ1NF
            M2RRZ3Ric3hlZjZEdVU2aEt0OGJtdUEK1cmKh1YyyKlOXbyU7DdvEwxsZmU/uUTS
            8UBzYQNLcb0B+EUWw45E/omt1are5burTjXSUDXf5esWZamu4jYLtA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-04T23:18:18Z"
    mac: ENC[AES256_GCM,data:1QqDtY08DbNAQgKcVfjFtGEgz5nR2W3EK3azvllbfWhBfIi2fjQndQwcO5yIRIEa9oYwNFQm5FHBviQutvqGpxOVDQOj05iuCcyHw+HDrZBNkgQSGxl9Ohk4UXADj3kuiCj+JMpSO7/xvGR/2pkluf2hws1fU5In41AQ7eXwXDo=,iv:s4K2YDKXzjxKPYo1hkh0EmeQFi5o0pVKgFFtfK17p4k=,tag:1pQ5x+mlgDLRHCyreTG0Sw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
