k3s_control_node: ENC[AES256_GCM,data:DYOJb/A=,iv:yybmXZsEhMpIKg3UEZD/lcvwOBa7Lka5HYQn6uOVFRo=,tag:j3EKr0j04k6rUgBb/Fc5nQ==,type:bool]
k3s_agent:
    node-ip: ENC[AES256_GCM,data:arp/GrmNxmJK40vTVHE=,iv:fFmpZON0ofhfaxnunPJVBj05RhZj1ClblE4oNd5cNsk=,tag:qy++lzeFzfusMa1ccaN1Qw==,type:str]
    pause-image: ENC[AES256_GCM,data:Zo9dbCmkevPxONWg2tnbGX2zGwVB/uLa3w==,iv:DYZBGyNrUDQfFfFSmJgWbVVIXJwF/xycmptC25heEi8=,tag:DatLbbA1xFd46dWQbnvGKQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wdhud9akfa4ua4urh3q6epn959wnd6yu0cmva7kdukx0kmvkxygst9ycau
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPRjI5MTQzWjZwbklmTXNJ
            Y3JsaGNjUzFlWUpDU01xWDR3di9QSmM0ZW1zCndzTlFSZUxsOHo5c0xDYld5YWNG
            MHpza2E0QXFnMERTa3ZndXIxTUxkbVkKLS0tICt4eWgxTU9hRThNdFJSdWxtUXdR
            Q250UVRoUWh2eFRhZy9xMzJ2dGdKbnMKsRLxau0zmSq/e8sycM4ZwYhmtUGBySQ8
            nlyMUx4O9aJw0/pL3n+2WZbxSpL50TU9zW+PK6GTJFfxsXvgIz+RXg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-04T22:44:35Z"
    mac: ENC[AES256_GCM,data:KWcw9OpO/g+P/B3L/bDpGSaBVKXd0m1InksyVbo6TG1YPBUkXuprrj8gzbjwuTJjh8/Z5krJ+6wFZmzaFj529jih77htg6VxmeyyWIujpXUHldCSMtS6qRU+9Jn/jMW+DDPBIiqDnhvtY0FiyYlSUztzJdq6UULRFtxh2ckgqnc=,iv:781RZLwiMK7z1CUuY1yy61uN+Hn6nMkvK9TIU0Oc9CY=,tag:o7c8kR+xAz9+0JNu1A1z4w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
