---
## Template image settings
template:
  name: UbuntuNobleCloudInit
  vmid: 900
  os_type: l26
  storage: local-lvm
  file:
    name: "noble-server-cloudimg-amd64.img"
    sum: "7b7f4d34bba4a6a819dbd67ae338b46141646de7b18ae3818a7aa178d383bfbb3e9e0197c545bb2d5fd5be7f8e55a7d449b285983ae86a09a294124bb97d3d5f"
  download:
    path: "/tmp"
    uri: "https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-amd64.img"
