---
- name: Upload cloud-init config file
  become: true
  ansible.builtin.template:
    src: templates/cloud-init.j2
    dest: /var/lib/vz/snippets/{{ template.vmid }}-cloud-init.yaml
    owner: root
    group: root
    mode: '0640'

- name: Create template from cloud-init image
  community.general.proxmox_kvm:
    api_host: "{{ pve.api.host }}"
    api_user: "{{ pve.api.user }}"
    api_password: "{{ pve.api.password }}"
    node: "{{ pve.node }}"
    name: "{{ template.name }}"
    vmid: "{{ template.vmid }}"
    tags:
      - ansible
      - template
    bios: ovmf
    boot: 'order=scsi0'
    cores: 2
    sockets: 1
    machine: q35
    memory: 4096
    agent: 1
    autostart: true
    ostype: "{{ template.os_type }}"
    efidisk0:
      storage: "{{ template.storage }}"
      format: raw
      efitype: 4m
      pre_enrolled_keys: 1
    serial:
      serial0: 'socket'
    vga: serial0
    scsihw: 'virtio-scsi-single'
    scsi:
      scsi0: "{{ template.storage }}:0,iothread=1,discard=on,import-from={{ template.download.path }}/{{ template.file.name }}"
    ide:
      ide2: '{{ template.storage }}:cloudinit'
    net:
      net0: 'virtio,bridge=vmbr0'
    cicustom: "vendor=local:snippets/{{ template.vmid }}-cloud-init.yaml"
    template: true
    timeout: 1000

- name: Clone VMs from cloud-init template
  community.general.proxmox_kvm:
    node: "{{ pve.node }}"
    api_user: "{{ pve.api.user }}"
    api_password: "{{ pve.api.password }}"
    api_host: "{{ pve.api.host }}"
    clone: "{{ template.name }}"
    full: true
    vmid: "{{ template.vmid }}"
    name: "{{ item.name }}"
    newid: "{{ item.vmid }}"
  loop: "{{ vms }}"

- name: Setup network / cloud-init settings
  vars:
    ssh_key_path: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519.pub"
  community.general.proxmox_kvm:
    node: "{{ pve.node }}"
    api_user: "{{ pve.api.user }}"
    api_password: "{{ pve.api.password }}"
    api_host: "{{ pve.api.host }}"
    vmid: "{{ item.vmid }}"
    tags:
      - ansible
      - k3s
      - control
    update: true
    cores: "{{ item.cpu.cores }}"
    memory: "{{ item.memory }}"
    sockets: "{{ item.cpu.sockets }}"
    searchdomains:
      - "{{ network.dns_server }}"
    ipconfig:
      ipconfig0: 'ip={{ item.ip_addr }},gw={{ network.gateway }}'
    ciuser: "{{ cloud_init.username }}"
    cipassword: "{{ cloud_init.password | password_hash }}"
    sshkeys: "{{ lookup('ansible.builtin.file', '{{ ssh_key_path }}') }}"
  loop: "{{ vms }}"

- name: Configure VM net
  become: true
  ansible.builtin.shell:
    cmd: qm set {{ item.vmid }} --net0 virtio={{ item.mac_addr }},bridge=vmbr0,tag={{ network.vlan_tag }},firewall=0
  loop: "{{ vms }}"

- name: Resize VM disk
  become: true
  ansible.builtin.shell:
    cmd: qm resize {{ item.vmid }} scsi0 {{ item.disk_size }}G
  loop: "{{ vms }}"

- name: Start VMs
  community.general.proxmox_kvm:
    node: "{{ pve.node }}"
    api_user: "{{ pve.api.user }}"
    api_password: "{{ pve.api.password }}"
    api_host: "{{ pve.api.host }}"
    vmid: "{{ item.vmid }}"
    state: started
    timeout: 1000
  loop: "{{ vms }}"
