---
- name: Ensure iommu is passed to grub options
  become: true
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX_DEFAULT='
    line: GRUB_CMDLINE_LINUX_DEFAULT="quiet iommu=pt"
    backup: true
  register: change_grub_res

- name: Update grub
  become: true
  ansible.builtin.shell: update-grub
  when: change_grub_res.changed

- name: Add vfio module
  become: true
  community.general.modprobe:
    name: vfio
    persistent: present
  register: vfio_res

- name: Add vfio_iommu_type1 module
  become: true
  community.general.modprobe:
    name: vfio_iommu_type1
    persistent: present
  register: vfio_iommu_type1_res

- name: Add vfio_pci module
  become: true
  community.general.modprobe:
    name: vfio_pci
    params: ids=10de:1c03,10de:10f1
    persistent: present
  register: vfio_pci_res

- name: Add nouveau softdep
  become: true
  ansible.builtin.lineinfile:
    path: /etc/modprobe.d/vfio_pci.conf
    line: "softdep nouveau pre: vfio-pci"

- name: Add nvidia softdep
  become: true
  ansible.builtin.lineinfile:
    path: /etc/modprobe.d/vfio_pci.conf
    line: "softdep nvidia pre: vfio-pci"

- name: Add nvidiafb softdep
  become: true
  ansible.builtin.lineinfile:
    path: /etc/modprobe.d/vfio_pci.conf
    line: "softdep nvidiafb pre: vfio-pci"

- name: Add nvidia_drm softdep
  become: true
  ansible.builtin.lineinfile:
    path: /etc/modprobe.d/vfio_pci.conf
    line: "softdep nvidia_drm pre: vfio-pci"

- name: Add drm softdep
  become: true
  ansible.builtin.lineinfile:
    path: /etc/modprobe.d/vfio_pci.conf
    line: "softdep drm pre: vfio-pci"

- name: Update initramfs
  become: true
  ansible.builtin.shell: update-initramfs -u -k all
  when: vfio_res.changed or vfio_iommu_type1_res.changed or vfio_pci_res.changed
  register: update_initramfs_res

- name: Reboot
  become: true
  ansible.builtin.reboot:
  when: change_grub_res.changed or update_initramfs_res.changed
