---
- name: Ensure packages are updated
  become: true
  ansible.builtin.apt:
    upgrade: yes
    update_cache: yes
  ignore_errors: true

- name: Ensure required libraries are installed
  become: true
  ansible.builtin.apt:
    name: 
      - python3-proxmoxer
      - python3-requests
    state: present
    update_cache: true
    install_recommends: false
