---
- name: Check that the cloudinit file exists
  ansible.builtin.stat:
    path: "{{ template.download.path }}/{{ template.file.name }}"
  register: stat_result

- name: Download cloud-init image
  ansible.builtin.get_url:
    url: "{{ template.download.uri }}"
    dest: "{{ template.download.path }}"
    mode: '0644'
    force: true
  when: not stat_result.stat.exists

- name: Ensure lxc template is present
  become: true
  ansible.builtin.shell:
    cmd: pveam download {{ lxc_template.storage }} {{ lxc_template.image }}
