pve_nodes_home:
  hosts:
    pve:

pve_vms:
  hosts:
    k3s-control-01:
    k3s-worker-01:
    k3s-worker-02:

pve_cts:
  hosts:
    postgresql:

k3s_nodes:
  children:
    control:
      hosts:
        k3s-control-01:
    worker:
      hosts:
        k3s-worker-01:
        k3s-worker-02:
