pve_nodes_home:
  hosts:
    pve:

pve_containers:
  hosts:
    postgresql:

k3s_cluster:
  children:
    control:
      hosts:
        k3s-control-01:
    worker:
      hosts:
        k3s-worker-01:
        k3s-worker-02:
