- name: Setup pve host
  hosts: pve
  tasks:
    - name: Base pve node setup
      include_role:
        name: nodes
    - name: Setup template and vm's
      include_role:
        name: vms
    - name: Setup lxc template and containers
      include_role:
        name: containers

- name: Setup postgresql
  hosts: postgresql
  tasks:
    - name: Install postgres
      include_role:
        name: postgresql

- name: Setup k3s
  hosts: k3s_nodes
  vars:
    k3s_server:
      datastore-endpoint: "{{ pg-endpoint }}"
  pre_tasks:
    - name: Set each node to be a control node
      ansible.builtin.set_fact:
        k3s_control_node: true
      when: "'control' in inventory_hostname"
  roles:
    - role: xanmanning.k3s
      k3s_become: true

