- name: Main playbook
  hosts: pve
  tasks:
    - name: Base pve node setup
      include_role:
        name: nodes
    - name: Setup template and vm's
      include_role:
        name: vms

- name: Setup k3s
  become: true
  hosts: k3s_cluster
  pre_tasks:
    - name: Set each node to be a control node
      ansible.builtin.set_fact:
        k3s_control_node: true
      when: inventory_hostname in ['k3s-control-01']
  roles:
    - role: xanmanning.k3s
      k3s_become: true
      k3s_etcd_datastore: true
      k3s_use_unsupported_config: true

