---
- name: Prepare pve node
  hosts: pve
  become: true
  gather_facts: true
  any_errors_fatal: true
  vars:
    ansible_port: "{{ pve.ansible_port }}"
    ansible_user: "{{ pve.ansible_user }}"
    kvm_template_filename: "{{ kvm_template.base_image_uri | urlsplit('path') | basename }}"
  tasks:
    - name: Ensures pve subscription block is removed
      ansible.builtin.include_tasks:
        file: tasks/pve-prompt.yaml

    - name: Ensure snippets directory exists
      ansible.builtin.file:
        path: /var/lib/vz/snippets
        state: directory
        mode: '0755'

    - name: Ensure pve packages are updated
      ansible.builtin.apt:
        upgrade: yes
        update_cache: yes
      ignore_errors: true

    - name: Ensure pve python libraries are installed
      ansible.builtin.apt:
        name: 
          - python3-proxmoxer
          - python3-requests
        state: present
        update_cache: true
        install_recommends: false

    - name: Ensure pve mounts are in place
      ansible.posix.mount:
        path: "{{ item.path }}"
        src: "{{ item.src }}"
        fstype: "{{ item.fstype }}"
        state: mounted
        opts: "{{ item.opts }}"
      loop: "{{ mounts }}"

    - name: Ensures GPU passthrough is configured
      ansible.builtin.include_tasks:
        file: tasks/gpu-passthrough.yaml

    - name: Ensures KVM template is configured
      ansible.builtin.include_tasks:
        file: tasks/kvm-template.yaml

    - name: Ensures LXC template is configured
      ansible.builtin.include_tasks:
        file: tasks/lxc-template.yaml

  handlers:
    - name: Reboot
      ansible.builtin.reboot:
        msg: Rebooting nodes
        reboot_timeout: 3600
