---
- name: Setup nodes and install k3s
  hosts: localhost
  gather_facts: false
  any_errors_fatal: true
  tasks:
    - name: Clone cilium-cli
      ansible.builtin.git:
        dest: "{{ cilium_cli_clone_path }}"
        repo: git@github.com:cilium/cilium-cli.git
        key_file: "{{ ssh_key_path }}"
      register: clone_res

    - when: clone_res.changed
      block:
      - name: Install cilium-cli
        environment:
          BINDIR: "{{ bin_install_path }}"
        community.general.make:
          chdir: "{{ cilium_repo_path }}"
          target: install

      - name: Install cilium
        ansible.builtin.shell:
          cmd: cilium install

    - name: Check if flux is already installed
      ansible.builtin.stat:
        path: "{{ bin_install_path }}/flux"
      register: flux_bin

    - when: not flux_bin.stat.exists
      block:
      - name: Download flux-cli installer
        ansible.builtin.get_url:
          url: https://fluxcd.io/install.sh
          dest: /tmp/install-flux.sh
          mode: 0755

      # doesn't get hackier than this lol
      - name: Ensure BIN_DIR gets applied
        ansible.builtin.lineinfile:
          path: /tmp/install-flux.sh
          regexp: '^BIN_DIR='
          line: "BIN_DIR={{ bin_install_path }}"

      - name: Install flux-cli
        #environment: # for some reason doesn't work
        #  BIN_DIR: "{{ bin_install_path }}"
        ansible.builtin.shell:
          cmd: /tmp/install-flux.sh

      - name: Install flux
        ansible.builtin.shell:
          cmd: flux install
